#!/usr/bin/env bash
set -euo pipefail

PASS="\033[32m✓\033[0m"
FAIL="\033[31m✗\033[0m"
BOLD="\033[1m"
RESET="\033[0m"

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  VAST Fraud Detection Demo — First-Time Setup       ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# Check if .env already exists
if [[ -f .env ]]; then
    read -rp "Configuration (.env) already exists. Re-run setup? [y/N] " confirm
    if [[ "${confirm,,}" != "y" ]]; then
        echo "Setup skipped. Run: make demo"
        exit 0
    fi
fi

# ── [1/6] Event Broker ──
echo ""
printf "${BOLD}[1/6] VAST Event Broker Configuration${RESET}\n"
read -rp "  Event Broker VIP or hostname: " VAST_HOST
read -rp "  Kafka port [9092]: " VAST_PORT
VAST_PORT="${VAST_PORT:-9092}"
VAST_BOOTSTRAP_SERVERS="${VAST_HOST}:${VAST_PORT}"

printf "  Testing connectivity..."
if nc -zw5 "$VAST_HOST" "$VAST_PORT" 2>/dev/null; then
    printf " ${PASS} Connected\n"
else
    printf " ${FAIL} Cannot reach ${VAST_HOST}:${VAST_PORT}\n"
    echo "  Check network/VPN and try again."
    exit 1
fi

# ── [2/6] VMS Credentials ──
echo ""
printf "${BOLD}[2/6] VAST VMS Credentials${RESET}\n"
read -rp "  VMS endpoint (https://...): " VAST_ENDPOINT
read -rp "  Access key: " VAST_ACCESS_KEY
read -rsp "  Secret key: " VAST_SECRET_KEY
echo ""

printf "  Testing API access..."
if python3 -c "
import vastdb
s = vastdb.connect(endpoint='${VAST_ENDPOINT}', access_key='${VAST_ACCESS_KEY}', secret_key='${VAST_SECRET_KEY}')
with s.transaction() as tx:
    tx.bucket('yg-bucket')
print('ok')
" 2>/dev/null | grep -q ok; then
    printf " ${PASS} Authenticated\n"
else
    printf " ${FAIL} Authentication failed\n"
    echo "  Check endpoint and credentials."
    exit 1
fi

# ── [3/6] Bucket & Schema ──
echo ""
printf "${BOLD}[3/6] VAST Bucket & Schema${RESET}\n"
read -rp "  Kafka bucket name [yg-bucket]: " VAST_KAFKA_BUCKET
VAST_KAFKA_BUCKET="${VAST_KAFKA_BUCKET:-yg-bucket}"
read -rp "  Kafka schema name [kafka_topics]: " VAST_KAFKA_SCHEMA
VAST_KAFKA_SCHEMA="${VAST_KAFKA_SCHEMA:-kafka_topics}"
read -rp "  Target schema name [fraud_detection]: " VAST_TARGET_SCHEMA
VAST_TARGET_SCHEMA="${VAST_TARGET_SCHEMA:-fraud_detection}"
printf "  ${PASS} Configuration noted\n"

# ── [4/6] Kafka Topics ──
echo ""
printf "${BOLD}[4/6] Kafka Topics${RESET}\n"
echo "  Topics must be created via VAST Admin UI (vastde CLI has dot-in-name issues)."
echo "  Go to: VAST Database → ${VAST_KAFKA_BUCKET} → Kafka-Compatible Broker Topics"
echo ""
for topic in fraud.transactions.raw fraud.transactions.scored fraud.alerts fraud.metrics; do
    if python3 -c "
from confluent_kafka.admin import AdminClient
a = AdminClient({'bootstrap.servers': '${VAST_BOOTSTRAP_SERVERS}'})
md = a.list_topics('${topic}', timeout=5)
if '${topic}' in md.topics:
    print('exists')
" 2>/dev/null | grep -q exists; then
        printf "  ${PASS} ${topic} exists\n"
    else
        printf "  ${FAIL} ${topic} — create it in VAST Admin UI\n"
    fi
done
echo ""
read -rp "  Press Enter once all topics are created... "

# ── [5/6] Blob Expansion ──
echo ""
printf "${BOLD}[5/6] Configuring Blob Expansion${RESET}\n"
PYTHONPATH=. python3 vast/blob_expansion_setup.py \
    --endpoint "$VAST_ENDPOINT" \
    --access-key "$VAST_ACCESS_KEY" \
    --secret-key "$VAST_SECRET_KEY" \
    --kafka-bucket "$VAST_KAFKA_BUCKET" \
    --kafka-schema "$VAST_KAFKA_SCHEMA" \
    --target-schema "$VAST_TARGET_SCHEMA" 2>&1 | while IFS= read -r line; do
    echo "  $line"
done

# ── [6/6] Save Configuration ──
echo ""
printf "${BOLD}[6/6] Saving Configuration${RESET}\n"

cat > .env << ENVEOF
# VAST Fraud Detection Demo Configuration
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# VAST Event Broker
VAST_BOOTSTRAP_SERVERS=${VAST_BOOTSTRAP_SERVERS}

# VAST VMS / S3 Credentials
VAST_ENDPOINT=${VAST_ENDPOINT}
VAST_ACCESS_KEY=${VAST_ACCESS_KEY}
VAST_SECRET_KEY=${VAST_SECRET_KEY}

# VAST Bucket & Schema
VAST_KAFKA_BUCKET=${VAST_KAFKA_BUCKET}
VAST_KAFKA_SCHEMA=${VAST_KAFKA_SCHEMA}
VAST_TARGET_SCHEMA=${VAST_TARGET_SCHEMA}

# Demo Settings
DEMO_TPS=1000
DEMO_DURATION=300
ENVEOF

printf "  ${PASS} .env written\n"

# Verify .gitignore
if ! grep -q "^\.env$" .gitignore 2>/dev/null; then
    echo ".env" >> .gitignore
    printf "  ${PASS} .env added to .gitignore\n"
else
    printf "  ${PASS} .env already in .gitignore\n"
fi

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  Setup complete!                                    ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  Run the demo:                                      ║"
echo "║    make demo          Full side-by-side demo        ║"
echo "║    make demo-vast     VAST pipeline only            ║"
echo "║    make demo-mode     Simulated data (no cluster)   ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
